FROM postgres:17.6

COPY ["./src/postgres/init.sql", "/docker-entrypoint-initdb.d/01-init-otel.sql"]
COPY ["./dynatrace/postgres/init.sql", "/docker-entrypoint-initdb.d/02-init-products.sql"]
COPY ["./dynatrace/postgres/statement_performance.sql", "/docker-entrypoint-initdb.d/03-statement-performance.sql"]

COPY ["./dynatrace/postgres/config.sh", "/docker-entrypoint-initdb.d/00-config.sh"]
RUN chmod +x /docker-entrypoint-initdb.d/00-config.sh

EXPOSE ${POSTGRES_PORT}
