image: europe-docker.pkg.dev/dynatrace-demoability/docker/cloud-backend-load-generator
tag: 1.2.0
resources:
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 50m
    memory: 50Mi
externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  remoteKey: argocd/astroshop-product-catalog-admin

envs:
  triggerErrorIntervalS:
    name: TRIGGER_ERROR_INTERVAL_S
    value: "120"
  triggerWarningIntervalS:
    name: TRIGGER_WARNING_INTERVAL_S
    value: "30"
