x-logging: &default-logging
  driver: json-file
  options:
    max-file: "5"
    max-size: "10m"

services:
  load-generator:
    image: ${IMAGE_NAME}:${DEMO_VERSION}
    build: .
    logging: *default-logging
