apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccountName }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.eksRoleArn }}"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-scaler
  namespace: "{{ .Release.Namespace }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-scaler-role
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-scaler-binding
  namespace: "{{ .Release.Namespace }}"
subjects:
  - kind: ServiceAccount
    name: deployment-scaler
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: deployment-scaler-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name consumer-service
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      serviceAccountName: "{{ .Values.serviceAccountName }}"
      containers:
        - name: astroshop-consumer-service
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          env: {{- include "mapToList" .Values.envs | nindent 10 }}
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 256Mi

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down-consumer-service
  namespace: astroshop-consumer-service
spec:
  schedule: "{{ .Values.scaleDownCronExpression }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: deployment-scaler
          containers:
            - name: kubectl
              image: "{{ .Values.kubectlImage }}:{{ .Values.kubectlImageTag }}"
              command:
                - /bin/sh
                - -c
                - kubectl scale deployment consumer-service --replicas=0 -n {{ .Release.Namespace }}
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-up-consumer-service
  namespace: astroshop-consumer-service
spec:
  schedule: "{{ .Values.scaleUpCronExpression }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: deployment-scaler
          containers:
            - name: kubectl
              image: "{{ .Values.kubectlImage }}:{{ .Values.kubectlImageTag }}"
              command:
                - /bin/sh
                - -c
                - kubectl scale deployment consumer-service --replicas=1 -n {{ .Release.Namespace }}
          restartPolicy: OnFailure
