name: PR build
on:
  pull_request:
    branches:
      - "main"
    paths:
      - .github/**
      - kubernetes-manifests/**
      - src/**
      - src-dt/**
      - charts/**
      - dynatrace/**
  workflow_dispatch:

  workflow_call:
    secrets:
      GAR_CREDENTIALS:
        required: true
      KUBECONFIG:
        required: true
      OQR_CLIENT_ID:
        required: true
      OQR_CLIENT_SECRET:
        required: true
      OQR_URL:
        required: true
      SNYK_API_TOKEN:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      SSO_URL:
        required: true

jobs:
  calc-version:
    uses: ./.github/workflows/reusable-calc-version.yaml

  build:
    if: needs.calc-version.outputs.already-released == 'false'
    needs: calc-version
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-build.yaml
    with:
      push: false
      is-pr: true
      version: ${{ needs.calc-version.outputs.version }}
    secrets: inherit
